CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE IF NOT EXISTS "users" (
  id SERIAL NOT NULL PRIMARY KEY ,
  username CITEXT NOT NULL UNIQUE ,
  email CITEXT NOT NULL UNIQUE ,
  password TEXT NOT NULL
);

