CREATE EXTENSION IF NOT EXISTS CITEXT;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tokens;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL NOT NULL PRIMARY KEY ,
  username CITEXT NOT NULL ,
  email CITEXT NOT NULL UNIQUE ,
  password citext NOT NULL ,
  enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS tokens (
  id SERIAL NOT NULL PRIMARY KEY,
  userr NUMERIC NOT NULL ,
  FOREIGN KEY (userr) REFERENCES users(id),
  token citext NOT NULL
);
